#! /bin/sh

NODE_EXEC=/usr/local/bin/node
#NODE_ENV="production"
NODE_ENV="development"
NODE_APP='app.js'
APP_DIR='/home/ubuntu/mtm';
#APP_DIR='/Users/zan/WebstormProjects/mtm';
PID_FILE=$APP_DIR/pid/app.pid
LOG_FILE=$APP_DIR/log/app.log
CONFIG_DIR=$APP_DIR/config

###############

# REDHAT chkconfig header

# chkconfig: - 58 74
# description: node-app is the script for starting a node app on boot.
### BEGIN INIT INFO
# Provides: node
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop node
# Description: Node process for app
### END INIT INFO


case "$1" in
    start)
        set -- $(pgrep -f 'node')
        pid=$1
        if [ $pid ]
        then
            echo "node process ${pid} exists, process is already running"
        else
            echo "Starting node app..."
            NODE_ENV=$NODE_ENV NODE_CONFIG_DIR=$CONFIG_DIR $NODE_EXEC $APP_DIR/$NODE_APP  1>$LOG_FILE 2>&1 &
            sleep 2
            if
                pgrep -f 'node'
            then
                echo "start successfully"
            else
                echo "start failed"
            fi
        fi
        ;;

    stop)
        set -- $(pgrep -f 'node')
        pid=$1
        if [ $pid ]
        then
            echo "Stopping $APP_DIR/$NODE_APP ..."
            echo "Killing ${pid}"
            kill ${pid};
            sleep 2
            if
                pgrep -f 'node'
            then
                echo "stop failed"
            else
                echo "stop successfully"
            fi
        else
            echo "no node process is running."
        fi
        ;;

    restart)
        set -- $(pgrep -f 'node')
        pid=$1
        if [ $pid ]
        then
            echo "Restarting $APP_DIR/$NODE_APP ..."
            echo "Killing ${pid}"
            kill ${pid};
            sleep 2
            if
                pgrep -f 'node'
            then
                echo "stop failed"
            else
                echo "stop successfully"
            fi
            NODE_ENV=$NODE_ENV NODE_CONFIG_DIR=$CONFIG_DIR $NODE_EXEC $APP_DIR/$NODE_APP  1>$LOG_FILE 2>&1 &
            sleep 2
            if
                pgrep -f 'node'
            then
                echo "start successfully"
            else
                echo "start failed"
            fi
            echo "Node restarted !"
        else
            echo "node process is not running"
        fi
        ;;

    status)
        set -- $(pgrep -f 'node')
        pid=$1
        if [ $pid ]
        then
            echo "node is running at pid: ${pid}"
        else
            echo "Node app stopped"
        fi
        ;;

    *)
        echo "Usage: /etc/init.d/node-app {start|stop|restart|status}"
    ;;
esac
